library remaths.v2;

import 'package:flutter/animation.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/physics.dart';
import 'dart:math' as math;
part 'v2/core/animation/config.dart';
part 'v2/node.dart';
part 'v2/core/shared/shared_value.dart';
part 'v2/core/animation/timing.dart';
part 'v2/core/animation/spring.dart';
part 'v2/core/animation/delay.dart';
part 'v2/core/animation/sequence.dart';
part 'v2/core/animation/setValue.dart';
part 'v2/core/animation/repeat.dart';
part 'v2/core/shared/details.dart';
part 'v2/core/shared/helpers.dart';
part 'v2/core/animation/interpolate.dart';
part 'v2/core/extension.dart';
part 'v2/core/animation/stagger.dart';
